# Generated by Django 5.0.4 on 2024-04-11 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5, 'Must contains at least 5 char')])),
                ('displayName', models.CharField(max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(5, 'Must contains at least 5 char')])),
                ('pongElo', models.PositiveIntegerField(default=200)),
                ('gunFightElo', models.PositiveIntegerField(default=200)),
                ('picture', models.CharField(max_length=25, null=True)),
                ('jwt_emitted', models.IntegerField(default=0)),
            ],
        ),
    ]
